# Generated by Django 5.2.3 on 2025-06-19 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_log', '0002_category_book_owner_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 18, 21, 12, 75916, tzinfo=datetime.timezone.utc)),
        ),
    ]
