# Generated by Django 5.2.3 on 2025-06-19 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_log', '0003_alter_book_startdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 18, 25, 3, 499181, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='book_log.category'),
        ),
    ]
