# Generated by Django 5.2.3 on 2025-06-21 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_log', '0004_alter_category_options_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 15, 11, 28, 828626, tzinfo=datetime.timezone.utc)),
        ),
    ]
